version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=app_db
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  app:
    build:
      context: node
    image: rafaelglv/app:latest
    container_name: app
    command: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks: 
      - node-network
    tty: true
    depends_on: 
      - db

  nginx:
    build: 
      context: nginx
    image: rafaelglv/nginx:latest
    container_name: nginx
    command: dockerize -wait tcp://app:3000 -timeout 20s nginx -g "daemon off;"
    networks:
      - node-network
    tty: true
    ports: 
      - "8080:80"
    depends_on:
      - app
      - db

networks:
  node-network:
    driver: bridge
